# Generated by Django 4.0.4 on 2022-04-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danceablity', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.FloatField()),
                ('loudness', models.FloatField()),
                ('valence', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('acounticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.FloatField()),
                ('time_signature', models.FloatField()),
            ],
        ),
    ]
